services:
  parser:
    build: 
      context: ./internal/parser/python
    ports:
      - "8000:8000"
    volumes:
      - ./internal/parser/python:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  backend:
    build: 
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PARSER_SERVICE_URL=http://parser:8000
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=visualdebugger
    depends_on:
      - parser
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend  # Path relative to where docker-compose.yml is located
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules  # Prevents local node_modules from mounting
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=visualdebugger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge